#!/bin/bash


dir=`dirname $0`/HoccerXO
sourcefiles=`find $dir -name "*.m"`

iconv -f UTF-8 -t UTF-16 HoccerXO/Localizations/en.lproj/Localizable.strings \
                       > HoccerXO/Localizations/en.lproj/ttt.strings
mv HoccerXO/Localizations/en.lproj/ttt.strings \
   HoccerXO/Localizations/en.lproj/Localizable.strings

genstrings $sourcefiles -o HoccerXO/Localizations/en.lproj

iconv -f UTF-16 -t UTF-8 HoccerXO/Localizations/en.lproj/Localizable.strings \
                       > HoccerXO/Localizations/en.lproj/ttt.strings
mv HoccerXO/Localizations/en.lproj/ttt.strings \
   HoccerXO/Localizations/en.lproj/Localizable.strings
